version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    platform: linux/amd64
    ports:
      - '22181:2181'
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    networks:
      - my-network

  kafka:
    image: wurstmeister/kafka:latest
    platform: linux/amd64
    ports:
      - '9092:9092'
      - '9093:9093'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: 'user-log-processing:20:1'
    depends_on:
      - zookeeper
    networks:
      - my-network

  mongo:
    image: mongo:4.4
    platform: linux/amd64
    ports:
      - '27017:27017'
    networks:
      - my-network

  kafdrop:
    image: obsidiandynamics/kafdrop
    platform: linux/amd64
    ports:
      - '9000:9000'
    environment:
      KAFKA_BROKER_CONNECT: 'kafka:9092'
    depends_on:
      - kafka
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
